### ISSUE TITLE
some explanations about the carry-less range coder

### ISSUE THREAD

**Issue by yaoqi-zd** [hiroki-kojima/CarryLessRangeCoder#1]
Hi, Thanks for sharing your code. I'm new to data compression and I don't quite understand the carry-less range coder which seems a littile different from the basic range coder, especially the renormalization part:
```
def _update_range(self, get_or_put):
        while self._low ^ (self._low + self._range) < self._top:
            get_or_put()
            self._range <<= self._precision
            self._low <<= self._precision

        while self._range < self._bot:
            get_or_put()
            self._range = (-self._low & (self._bot - 1)) << self._precision
            self._low <<= self._precision
```
would you mind to post any links that can explain the principle of carry-less range coder?
Thanks!

**Comment by hiroki-kojima** [comment]
@yaoqi-zd 
I couldn't find any good documentation explaining the principles.
[Here](https://fastapi.metacpan.org/source/SALVA/Compress-PPMd-0.10/Coder.hpp)'s an implementation by Dmitry Subbotin (author of the Carryless Rangecoder).

**Comment by diegodox** [comment]
I found [this link](http://www.compression.ru/fido/ru.compress.0029.htm#19) was referenced as the `Carryless rangecoder` in [this paper](https://ci.nii.ac.jp/naid/110003224959/).

**Comment by yaoqi-zd** [comment]
@hiroki-kojima @diegodox Thank you so much, I'll follow these links to checkout
